### ISSUE TITLE
Separate build for use in testing?

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/matplotlib-feedstock#110]
So for testing, matplotlib builds against an internal copy of freetype 2.6.1. Are there any votes against me adding a branch and build creating conda-forge packages linked against that copy? (They would obviously go under a different label.)

This would help me a great deal doing CI on metpy and its plotting tests, which have now broken on AppVeyor due to the move to freetype 2.7.

**Comment by ocefpaf** [comment]
I don't have anything against it. Let me know if you have the rights to create the `branch`.

(Sorry it took so long for me to notice this! Maybe you no longer need this :flushed:)

**Comment by ocefpaf** [comment]
@dopplershift I guess this can be closed, right? If not please re-open.

**Comment by dopplershift** [comment]
Kinda. I can't get them on windows until 2.1 releases...

**Comment by dopplershift** [comment]
Ok, 2.1 is out so I should be able to get around to making this work now.

**Comment by QuLogic** [comment]
Not sure about Windows, but looks like it needs an update for mpl 3?

**Comment by ocefpaf** [comment]
Can we close this issue? Looks like https://github.com/SciTools/cartopy/pull/1130 has everything you nee, right?

**Comment by dopplershift** [comment]
I'll close it out once #192 is in and I confirm all the packages seem fine. I was noticing some weird issues on my mac, probably related to what was fixed in #191.

**Comment by dopplershift** [comment]
Everything looks good here now.
