### ISSUE TITLE
no sample_data directory

### ISSUE THREAD

**Issue by electronwill** [conda-forge/matplotlib-feedstock#116]
After "conda install matplotlib" in a new environment "ls ~/miniconda3/envs/tmp/lib/python2.7/site-packages/matplotlib/mpl-data/sample_data/" works. After "conda install -c conda-forge matplotlib" in a new environment the directory is not found. I'm not sure if this is accidental or deliberate. Can someone here please help me understand the difference?

**Comment by electronwill** [comment]
On Google I found a previous mention of this at https://github.com/matplotlib/matplotlib/issues/8194 .

**Comment by ocefpaf** [comment]
We started packaging the mpl data in a separate package recently. Try installing `mpl_sample_data`.

**Comment by electronwill** [comment]
Got it. Thank you!

**Comment by baeyeba** [comment]
Data is available when installing mpl_sample_data but in the directory _**mpl_data**_ itself, while get_sample_data expect it to be in subdirectory _**sample_data**_!

**Comment by xu-song** [comment]
```
conda install -c conda-forge mpl_sample_data 
```
