### ISSUE TITLE
Cannot update to MPL v2.1.1 on Anaconda

### ISSUE THREAD

**Issue by rayosborn** [conda-forge/matplotlib-feedstock#136]
### Bug report

**Bug summary**

Although I was able to update to Matplotlib v2.1.1 using `conda update matplotlib`, *i.e.*, on the default channel, I could not import `matplotlib.pyplot` because the installed version of `libpng` is not high enough. Attempting to update `libpng` to v1.6.34 (the highest available on condo-forge) causes conda to downgrade Matplotlib to v2.1.0. I posted this as a [Matplotlib issue](https://github.com/matplotlib/matplotlib/issues/9980), but was told that this was a more appropriate forum. 

**Code for reproduction**

```python
Python 3.6.1 |Anaconda custom (x86_64)| (default, May 11 2017, 13:04:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
```

**Actual outcome**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rosborn/anaconda/lib/python3.6/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/Users/rosborn/anaconda/lib/python3.6/site-packages/matplotlib/colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "/Users/rosborn/anaconda/lib/python3.6/site-packages/matplotlib/contour.py", line 21, in <module>
    import matplotlib.font_manager as font_manager
  File "/Users/rosborn/anaconda/lib/python3.6/site-packages/matplotlib/font_manager.py", line 58, in <module>
    from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
ImportError: dlopen(/Users/rosborn/anaconda/lib/python3.6/site-packages/matplotlib/ft2font.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libpng16.16.dylib
  Referenced from: /Users/rosborn/anaconda/lib/libfreetype.6.dylib
  Reason: Incompatible library version: libfreetype.6.dylib requires version 45.0.0 or later, but libpng16.16.dylib provides version 44.0.0
```
Here is the result of trying to update `libpng`.
```
$ conda update -c conda-forge libpng
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /Users/rosborn/anaconda:

The following packages will be UPDATED:

    libpng:     1.6.27-0                 --> 1.6.34-0     conda-forge

The following packages will be DOWNGRADED:

    freetype:   2.7-2        conda-forge --> 2.7-1        conda-forge
    matplotlib: 2.1.1-py36_0 conda-forge --> 2.1.0-py36_0 conda-forge
```

**Matplotlib version**
  * Operating system: Mac OS X 10.12.6
  * Matplotlib version: 2.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX and PyQt5
  * Python version: 3.6.1

**Comment by rayosborn** [comment]
Can someone confirm that this issue page is monitored by anyone? There doesn't seem to have been any activity since September, and this is a potentially serious issue for me at least.

**Comment by ocefpaf** [comment]
This looks like a case of mixing channels. Please read: https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels

**Comment by rayosborn** [comment]
Thanks. Although I never got any feedback here, it may have been quietly fixed - there seems to be a new build number for the Matplotlib v2.1.1 conda release, which may explain why I was just now able to upgrade without it complaining about the libpng version. I'll close the issue for now.

**Comment by IvanChaperot** [comment]
I have a very similar issue with a Matplotlib install using Anaconda.

**Here is the code (using Jupyter on MacOs HighSierra)**
`import matplotlib.pyplot as plt`

**Here is the result:**

~/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py in <module>()
     30 from cycler import cycler
     31 import matplotlib
---> 32 import matplotlib.colorbar
     33 from matplotlib import style
     34 from matplotlib import _pylab_helpers, interactive

~/anaconda3/lib/python3.6/site-packages/matplotlib/colorbar.py in <module>()
     34 import matplotlib.collections as collections
     35 import matplotlib.colors as colors
---> 36 import matplotlib.contour as contour
     37 import matplotlib.cm as cm
     38 import matplotlib.gridspec as gridspec

~/anaconda3/lib/python3.6/site-packages/matplotlib/contour.py in <module>()
     19 import matplotlib.colors as colors
     20 import matplotlib.collections as mcoll
---> 21 import matplotlib.font_manager as font_manager
     22 import matplotlib.text as text
     23 import matplotlib.cbook as cbook

~/anaconda3/lib/python3.6/site-packages/matplotlib/font_manager.py in <module>()
     56 
     57 import matplotlib
---> 58 from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
     59 from matplotlib.compat import subprocess
     60 from matplotlib.fontconfig_pattern import (

ImportError: dlopen(/Users/Ivan/anaconda3/lib/python3.6/site-packages/matplotlib/ft2font.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libfreetype.6.dylib
  Referenced from: /Users/Ivan/anaconda3/lib/python3.6/site-packages/matplotlib/ft2font.cpython-36m-darwin.so
  Reason: Incompatible library version: ft2font.cpython-36m-darwin.so requires version 22.0.0 or later, but libfreetype.6.dylib provides version 21.0.0


**I tried upgrading the package without success:**

conda update -c conda-forge libpng
Solving environment: done

# All requested packages already installed.

It seems that I need to somewhat force update the installation of the version for libfreetype.6.dylib but don't know how to do it. Any suggestion?

**Comment by Ilyushin** [comment]
@IvanChaperot Did you try `conda update matplotlib`? I had the same error, and it helped me.

**Comment by stephaniemdavis** [comment]
@rayosborn @IvanChaperot: Per @Ilyushin, I ran conda update matplotlib and it worked. Thank You

**Comment by Kalsoomalik** [comment]
`conda update matplotlib` didn't work for me

**Comment by stephaniemdavis** [comment]
@Kalsoomalik - would you be able to show us the environment (Jupyter notebooks, Spyder,command line) you're working in? It makes a big difference. Also, please show your code, including error messages, you're receiving.
Thanks

**Comment by jgcalmario** [comment]
KeyError: 'PROJ_LIB'
