### ISSUE TITLE
2.1.1 py27/35_1 is broken 

### ISSUE THREAD

**Issue by jochym** [conda-forge/matplotlib-feedstock#138]
See the results of this build:
https://circleci.com/workflow-run/0598971a-a956-4eaa-ba62-2e00bb7b15dc
the stdc++ is missing for _contour.so 
After pinning to previous build (_0) all is fine again.

**Comment by jakirkham** [comment]
Yep, working on it. ( https://github.com/conda-forge/matplotlib-feedstock/pull/137 )

**Comment by jochym** [comment]
Thanks
