### ISSUE TITLE
Matplotlib Import Error: incompatible library version (libfreetype.6.dylib)

### ISSUE THREAD

**Issue by IvanChaperot** [conda-forge/matplotlib-feedstock#139]
I am struggling with an import of a library by Matplotlib and cannot figure out how to manage the version correctly.

**The environment was created by Anaconda on a MacOS (HighSierra). The import command is executed in a Jupyter notebook:**
`import matplotlib.pyplot as plt`

**It leads to:**
~/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py in <module>()
     30 from cycler import cycler
     31 import matplotlib
---> 32 import matplotlib.colorbar
     33 from matplotlib import style
     34 from matplotlib import _pylab_helpers, interactive

~/anaconda3/lib/python3.6/site-packages/matplotlib/colorbar.py in <module>()
     34 import matplotlib.collections as collections
     35 import matplotlib.colors as colors
---> 36 import matplotlib.contour as contour
     37 import matplotlib.cm as cm
     38 import matplotlib.gridspec as gridspec

~/anaconda3/lib/python3.6/site-packages/matplotlib/contour.py in <module>()
     19 import matplotlib.colors as colors
     20 import matplotlib.collections as mcoll
---> 21 import matplotlib.font_manager as font_manager
     22 import matplotlib.text as text
     23 import matplotlib.cbook as cbook

~/anaconda3/lib/python3.6/site-packages/matplotlib/font_manager.py in <module>()
     56 
     57 import matplotlib
---> 58 from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
     59 from matplotlib.compat import subprocess
     60 from matplotlib.fontconfig_pattern import (

ImportError: dlopen(/Users/Ivan/anaconda3/lib/python3.6/site-packages/matplotlib/ft2font.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libfreetype.6.dylib
  Referenced from: /Users/Ivan/anaconda3/lib/python3.6/site-packages/matplotlib/ft2font.cpython-36m-darwin.so
  Reason: Incompatible library version: ft2font.cpython-36m-darwin.so requires version 22.0.0 or later, but libfreetype.6.dylib provides version 21.0.0

** I tried different solutions, such as upgrading packages, to no avail **

(patent-landscape) bash-3.2$ conda update freetype
Solving environment: done

 All requested packages already installed.

(patent-landscape) bash-3.2$ conda update -c conda-forge libpng
Solving environment: done

 All requested packages already installed.

** I understand from other posts there may be some channel priority errors but don't know how to solve that. Here are the installed packages in the "patent-landscape" environment (retrieved with conda list)  **

appnope                   0.1.0                    py35_0    conda-forge
backports                 1.0                      py35_1    conda-forge
backports.functools_lru_cache 1.4                      py35_1    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    2.0.0                    py35_0    conda-forge
bleach                    1.5.0                     <pip>
ca-certificates           2017.11.5                     0    conda-forge
cachetools                2.0.1                     <pip>
certifi                   2017.11.5                py35_0    conda-forge
chardet                   3.0.4                     <pip>
clangdev                  5.0.0                 default_0    conda-forge
cycler                    0.10.0                   py35_0    conda-forge
decorator                 4.1.2                    py35_0    conda-forge
dill                      0.2.7.1                   <pip>
entrypoints               0.2.3                    py35_1    conda-forge
enum34                    1.1.6                     <pip>
freetype                  2.8.1                         0    conda-forge
future                    0.16.0                    <pip>
gapic-google-cloud-datastore-v1 0.15.3                    <pip>
gapic-google-cloud-error-reporting-v1beta1 0.15.3                    <pip>
gapic-google-cloud-logging-v2 0.91.3                    <pip>
google-api-core           0.1.4                     <pip>
google-api-python-client  1.6.4                     <pip>
google-auth               1.3.0                     <pip>
google-auth-oauthlib      0.2.0                     <pip>
google-cloud              0.32.0                    <pip>
google-cloud-bigquery     0.28.0                    <pip>
google-cloud-bigquery-datatransfer 0.1.0                     <pip>
google-cloud-bigtable     0.28.1                    <pip>
google-cloud-container    0.1.0                     <pip>
google-cloud-core         0.28.0                    <pip>
google-cloud-datastore    1.4.0                     <pip>
google-cloud-dns          0.28.0                    <pip>
google-cloud-error-reporting 0.28.0                    <pip>
google-cloud-firestore    0.28.0                    <pip>
google-cloud-language     1.0.0                     <pip>
google-cloud-logging      1.4.0                     <pip>
google-cloud-monitoring   0.28.0                    <pip>
google-cloud-pubsub       0.30.1                    <pip>
google-cloud-resource-manager 0.28.0                    <pip>
google-cloud-runtimeconfig 0.28.0                    <pip>
google-cloud-spanner      0.29.0                    <pip>
google-cloud-speech       0.30.0                    <pip>
google-cloud-storage      1.6.0                     <pip>
google-cloud-trace        0.17.0                    <pip>
google-cloud-translate    1.3.0                     <pip>
google-cloud-videointelligence 1.0.0                     <pip>
google-cloud-vision       0.29.0                    <pip>
google-gax                0.15.16                   <pip>
google-resumable-media    0.3.1                     <pip>
googleapis-common-protos  1.5.3                     <pip>
grpc-google-iam-v1        0.11.4                    <pip>
grpcio                    1.8.4                     <pip>
h5py                      2.7.1                    py35_2    conda-forge
hdf5                      1.10.1                        1    conda-forge
html5lib                  0.9999999                 <pip>
html5lib                  1.0.1                      py_0    conda-forge
httplib2                  0.10.3                    <pip>
icu                       58.2                          0    conda-forge
idna                      2.6                       <pip>
intel-openmp              2018.0.0             h8158457_8  
ipykernel                 4.7.0                    py35_0    conda-forge
ipython                   6.2.1                    py35_1    conda-forge
ipython_genutils          0.2.0                    py35_0    conda-forge
ipywidgets                7.1.0                    py35_0    conda-forge
jedi                      0.10.2                   py35_0    conda-forge
jinja2                    2.10                     py35_0    conda-forge
jpeg                      9b                            2    conda-forge
jsonschema                2.6.0                    py35_0    conda-forge
jupyter                   1.0.0                    py35_0    conda-forge
jupyter_client            5.2.1                    py35_0    conda-forge
jupyter_console           5.2.0                    py35_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
keras                     2.0.9                    py35_0    conda-forge
libcxx                    5.0.0                         0    conda-forge
libgfortran               3.0.0                         0    conda-forge
libiconv                  1.15                          0    conda-forge
libpng                    1.6.34                        0    conda-forge
libsodium                 1.0.15                        1    conda-forge
libxml2                   2.9.7                         0    conda-forge
llvmdev                   5.0.0                 default_0    conda-forge
Markdown                  2.6.11                    <pip>
markupsafe                1.0                      py35_0    conda-forge
matplotlib                2.1.1                    py35_2    conda-forge
mistune                   0.8.3                      py_0    conda-forge
mkl                       2018.0.1             hfbd8650_4  
mock                      2.0.0                    py35_0    conda-forge
nb_conda                  2.2.1                    py35_0    conda-forge
nb_conda_kernels          2.1.0                    py35_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py35_0    conda-forge
ncurses                   5.9                          10    conda-forge
notebook                  5.2.2                    py35_1    conda-forge
numpy                     1.14.0                    <pip>
numpy                     1.14.0          py35_blas_openblas_200  [blas_openblas]  conda-forge
oauth2client              3.0.0                     <pip>
oauthlib                  2.0.6                     <pip>
openblas                  0.2.20                        6    conda-forge
openssl                   1.0.2n                        0    conda-forge
pandas                    0.22.0                    <pip>
pandas                    0.22.0                   py35_0    conda-forge
pandas-gbq                0.3.0                     <pip>
pandoc                    2.1                           0    conda-forge
pandocfilters             1.4.1                    py35_0    conda-forge
patsy                     0.5.0                    py35_0    conda-forge
pbr                       3.1.1                    py35_0    conda-forge
pexpect                   4.3.1                    py35_0    conda-forge
pickleshare               0.7.4                    py35_0    conda-forge
Pillow                    5.0.0                     <pip>
pip                       9.0.1                    py35_1    conda-forge
ply                       3.8                       <pip>
prompt_toolkit            1.0.15                   py35_0    conda-forge
proto-google-cloud-datastore-v1 0.90.4                    <pip>
proto-google-cloud-error-reporting-v1beta1 0.15.3                    <pip>
proto-google-cloud-logging-v2 0.91.3                    <pip>
protobuf                  3.5.1                    py35_3    conda-forge
protobuf                  3.5.1                     <pip>
psutil                    5.4.3                     <pip>
ptyprocess                0.5.2                    py35_0    conda-forge
pyasn1                    0.4.2                     <pip>
pyasn1-modules            0.2.1                     <pip>
pygments                  2.2.0                    py35_0    conda-forge
pyparsing                 2.2.0                    py35_0    conda-forge
pyqt                      5.6.0                    py35_4    conda-forge
python                    3.5.4                         3    conda-forge
python-dateutil           2.6.1                    py35_0    conda-forge
pytz                      2017.3                     py_2    conda-forge
pyyaml                    3.12                     py35_1    conda-forge
pyzmq                     16.0.2                   py35_3    conda-forge
qt                        5.6.2                h9e3eb04_4    conda-forge
qtconsole                 4.3.1                    py35_0    conda-forge
readline                  7.0                           0    conda-forge
requests                  2.18.4                    <pip>
requests-oauthlib         0.8.0                     <pip>
rsa                       3.4.2                     <pip>
scikit-learn              0.19.1          py35_blas_openblas_201  [blas_openblas]  conda-forge
scipy                     1.0.0           py35_blas_openblas_201  [blas_openblas]  conda-forge
seaborn                   0.8.1                    py35_0    conda-forge
setuptools                38.4.0                   py35_0    conda-forge
simplegeneric             0.8.1                    py35_0    conda-forge
sip                       4.18                     py35_1    conda-forge
six                       1.11.0                   py35_1    conda-forge
sqlite                    3.20.1                        2    conda-forge
statsmodels               0.8.0                    py35_0    conda-forge
tensorflow                1.0.0                    py35_0    conda-forge
tensorflow                1.4.1                     <pip>
tensorflow-tensorboard    0.4.0rc3                  <pip>
terminado                 0.8.1                    py35_0    conda-forge
testpath                  0.3.1                    py35_0    conda-forge
tflearn                   0.3.2                     <pip>
tk                        8.6.7                         0    conda-forge
tornado                   4.5.3                    py35_0    conda-forge
traitlets                 4.3.2                    py35_0    conda-forge
uritemplate               3.0.0                     <pip>
urllib3                   1.22                      <pip>
wcwidth                   0.1.7                    py35_0    conda-forge
webencodings              0.5                      py35_0    conda-forge
Werkzeug                  0.14.1                    <pip>
wheel                     0.30.0                   py35_2    conda-forge
widgetsnbextension        3.1.0                    py35_0    conda-forge
xz                        5.2.3                         0    conda-forge
yaml                      0.1.7                         0    conda-forge
zeromq                    4.2.1                         1    conda-forge
zlib                      1.2.11                        0    conda-forge

**Comment by IvanChaperot** [comment]
I found out that I made a rookie mistake. I was executing the wrong kernel with Jupyter. I switched to the correct kernel and this solved the issue (the conda list and conda upgrade commands were launched with the correct environment, but Jupyter was executing the notebook in a different kernel).

I will close the issue now.

**Comment by moonshoes87** [comment]
@IvanChaperot, I am having the same problem, but restarting the kernel etc. has not helped me.  Do you mind giving some more detail on how this occurred and how you fixed it?

**Comment by IvanChaperot** [comment]
my problem was my incorrect use of the Jutpyer. When I launched Jupyter from the Anaconda navigator, I thought it would automatically start in the environment I selected in Anaconda.

That was a mistake... 

Indeed, if you look at the top right of the Jupyter window, there is an indication of the Kernel that is currently running. If this is not the correct Kernel, you can change the Kernel in Jupyter by going to the Kernel menu.

That fixed the error for me. By using the correct Kernel, it loaded the correct version of Python and the librairies.

**Comment by pankajb64** [comment]
I know this comment is very late, but I rant into a similar issue and can confirm that you need to run the version of Jupyter installed in your environment. I was running the jupyter from the parent miniconda environment and was using `nb_conda` to switch to a kernel of my environment, but I was still facing the above error. Only by installing jupyter in my environment and running that did I manage to get past the error.
