### ISSUE TITLE
Build/run dependencies

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/matplotlib-feedstock#14]
`libpng` is listed as a dependency on all platforms at build time, but `unix` only at run time.

**Comment by pelson** [comment]
Agreed. I don't know why that is. @janschulz - do you know of the motivation for skipping the libpng dependency at runtime on Windows?

**Comment by janschulz** [comment]
This was also changed in the mpl one: https://github.com/matplotlib/matplotlib/pull/6116

The mpl one is based (in parts) on this recipe and I don't know where this restriction came from. It looks like a "is that now statically compiled in or not" thingy...

Questions like this are the reason why I would really like to see the recipe for the mpl package included in "default"... Even if it is not in the current format :-/

**Comment by janschulz** [comment]
IMO this recipe should be "pulled" from the current mpl repo (in `CI/conda_recipe`) and any additional changes should be synced with mpl. And if someone has access to Continuums mpl recipe, that one should be used to overwrite both this feedstock and mpl :-)

**Comment by ocefpaf** [comment]
Fixed in #15
