### ISSUE TITLE
import matplotlib.pyplot will crash after import tensorflow.slim

### ISSUE THREAD

**Issue by neutronest** [conda-forge/matplotlib-feedstock#144]
**issue report**
In the docker image "continuumio/anaconda3:5.0.1" environment, after using anaconda-project to build up a python project and install python3.5, matplotlib and tensorflow, an error "**dlopen: cannot load any more object with static TLS**" will happen if you first import tensorflow.contrib.slim then import  matplotlib.pyplot. However, if you try to import slim and matplotlib again with the same order as above again in another python progress, nothing will happen and everything seems ok. 

**Environment info:** 
docker with image continuumio/anaconda3:5.0.1
use anaconda-project and conda to manage packages install.

Full steps and codes as follow:
``` bash
$ docker run -t -i continuumio/anaconda3:5.0.1 /bin/bash
```

``` bash
/home#  apt-get -qq update && apt-get install -y build-essential libglu1-mesa libgtk2.0-0
```

``` bash
/home# mkdir foobar && cd foobar
```

``` bash
/home/foobar# anaconda-project init
Project configuration is in /home/foobar/anaconda-project.yml
```

``` bash
/home/foobar# anaconda-project add-packages python=3.5 matplotlib tensorflow
Fetching package metadata ...........
Solving package specifications: .
... (install packages)
tensorflow-1.4 100% |###############################| Time: 0:00:00   1.66 MB/s
#
# To activate this environment, use:
# > source activate /home/foobar/envs/default
#
# To deactivate an active environment, use:
# > source deactivate
#
Using Conda environment /home/foobar/envs/default.
Added packages to project file: python=3.5, matplotlib, tensorflow.
```

``` bash
/home/foobar# source activate envs/default/
```

``` bash
(envs/default/)/home/foobar# python
Python 3.5.4 |Anaconda custom (64-bit)| (default, Nov 20 2017, 18:44:38)
GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> from tensorflow.contrib import slim
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/foobar/envs/default/lib/python3.5/site-packages/matplotlib/pyplot.py", line 116, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/foobar/envs/default/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "/home/foobar/envs/default/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import (
  File "/home/foobar/envs/default/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 18, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/home/foobar/envs/default/lib/python3.5/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/home/foobar/envs/default/lib/python3.5/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 56, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/home/foobar/envs/default/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: dlopen: cannot load any more object with static TLS`
```

However, everything is ok when you run it at second time.
```bash
(envs/default/)/home/foobar# python
Python 3.5.4 |Anaconda custom (64-bit)| (default, Nov 20 2017, 18:44:38)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> from tensorflow.contrib import slim
>>> import matplotlib.pyplot as plt
>>>
```

Some tricks may be useful for a workaround such as import matplotlib first (similar and related issue: https://github.com/tensorflow/models/issues/523), I wonder if exist a pure solution or patch to solve it.

**Comment by jakirkham** [comment]
My recommendation would be to try and refine this issue further. As it is this will be hard for anyone to solve (assuming they have the time to dig in that deep).

For instance, the traceback suggests PyQt5 is involved. Does replacing `matplotlib` with that `PyQt5` import reproduce the issue? What is the minimum number of things that need to be imported from `PyQt5` to cause the issue. Does the issue happen with only `matplotlib`/`PyQt5` being imported? Same questions about refining `tensorflow` imports. And so on.

Also is this actually using `conda-forge` packages? It looks like it is using packages from `defaults` based on your setup. Could you please check? If it's not conda-forge's packages, would refer you to the Anaconda team for help.

**Comment by ocefpaf** [comment]
Closing this as stale (and impossible to debug with more info).
