### ISSUE TITLE
libfreetype.6.dylib version 22.0.0 was required after updating matplotlib

### ISSUE THREAD

**Issue by zzygyx9119** [conda-forge/matplotlib-feedstock#156]
Dear All,

After running the command "conda install -c conda-forge matplotlib" to update the matplotlib on my mac (High sierra, version 10.13.3), I got the following error message when trying to do "import matplotlib.pyplot as plt":

> "ImportError: dlopen(/Users/jeff/anaconda2/lib/python2.7/site-packages/matplotlib/ft2font.so, 2): Library not loaded: @rpath/libfreetype.6.dylib
>   Referenced from: /Users/jeff/anaconda2/lib/python2.7/site-packages/matplotlib/ft2font.so
>   Reason: Incompatible library version: ft2font.so requires version 22.0.0 or later, but libfreetype.6.dylib provides version 21.0.0"

I never met with this problem before, and couldn't find solutions online for this issue. Would you please help me out? 

Your kind help mould be greatly appreciated!

Jeff

**Comment by zzygyx9119** [comment]
Thanks！ I actually solved my current problem by going back to a older version of matplotlib by doing:

Condo remove matplotlib

conda install matplotlib=2.1.1

conda install -c anaconda seaborn

this way, i managed to be able to continue my ongoing projects.

**Comment by zzygyx9119** [comment]
here is my "conda list":  (unfortunately, this is the list after i went back to older version matplotlib

# Name                    Version                   Build  Channel
_license                  1.1                      py27_1  
alabaster                 0.7.9                    py27_0  
anaconda                  custom           py27h2cfa9e9_0  
anaconda-client           1.6.2                    py27_0  
anaconda-navigator        1.5.1                    py27_0  
anaconda-project          0.4.1                    py27_0  
appnope                   0.1.0                    py27_0  
appscript                 1.0.1                    py27_0  
argcomplete               1.0.0                    py27_1  
astroid                   1.4.9                    py27_0  
astropy                   2.0.2            py27heac18bc_4  
babel                     2.3.4                    py27_0  
backports                 1.0                      py27_0  
backports.functools_lru_cache 1.5                      py27_1    anaconda
backports_abc             0.5                      py27_0  
bcftools                  1.4                           0    bioconda
beautifulsoup4            4.5.3                    py27_0  
binstar                   0.12                          2  
biopython                 1.71             py27h1702cab_0    anaconda
bitarray                  0.8.1                    py27_0  
blaze                     0.10.1                   py27_0  
bokeh                     0.12.4                   py27_0  
boto                      2.45.0                   py27_0  
bottleneck                1.2.1            py27h71f98a3_0    anaconda
bzip2                     1.0.6                         3  
ca-certificates           2018.03.07                    0    anaconda
cdecimal                  2.3                      py27_2  
certifi                   2018.4.16                py27_0    anaconda
cffi                      1.9.1                    py27_0  
chardet                   2.3.0                    py27_0  
chest                     0.2.3                    py27_0  
click                     6.7                      py27_0  
cloudpickle               0.2.2                    py27_0  
clyent                    1.2.2                    py27_0  
colorama                  0.3.7                    py27_0  
conda                     4.5.1                    py27_0    anaconda
conda-env                 2.6.0                h36134e3_0    anaconda
configobj                 5.0.6                    py27_0  
configparser              3.5.0                    py27_0  
contextlib2               0.5.4                    py27_0  
coursera-dl               0.8.0                    py27_0    conda-forge
cruzdb                    0.5.6                    py27_0    natapol
cryptography              1.7.1                    py27_0  
curl                      7.52.1                        0  
cycler                    0.10.0                   py27_0  
cython                    0.25.2                   py27_0  
cytoolz                   0.8.2                    py27_0  
dask                      0.13.0                   py27_0  
datashape                 0.5.4                    py27_0  
decorator                 4.0.11                   py27_0  
dill                      0.2.5                    py27_0  
docutils                  0.13.1                   py27_0  
edx-dl                    0.1.7                     <pip>
entrypoints               0.2.2                    py27_0  
enum34                    1.1.6                    py27_0  
et_xmlfile                1.0.1                    py27_0  
fastcache                 1.0.2                    py27_1  
flask                     0.12                     py27_0  
flask-cors                3.0.2                    py27_0  
freetype                  2.8                  h12048fb_1    anaconda
funcsigs                  1.0.2                    py27_0  
functools32               3.2.3.2                  py27_0  
futures                   3.0.5                    py27_0  
get_terminal_size         1.0.0                    py27_0  
gevent                    1.2.1                    py27_0  
greenlet                  0.4.11                   py27_0  
grin                      1.2.1                    py27_3  
h5py                      2.7.1            py27h75626f5_0    anaconda
hdf5                      1.10.1               ha036c08_1    anaconda
heapdict                  1.0.0                    py27_1  
html5lib                  1.0.1                     <pip>
htslib                    1.4                           0    bioconda
icu                       54.1                          0  
idna                      2.2                      py27_0  
imageio                   2.3.0                    py27_0    anaconda
imagesize                 0.7.1                    py27_0  
intel-openmp              2018.0.0                      8    anaconda
ipaddress                 1.0.18                   py27_0  
ipykernel                 4.5.2                    py27_0  
ipython                   5.1.0                    py27_1  
ipython_genutils          0.1.0                    py27_0  
ipywidgets                5.2.2                    py27_1  
isort                     4.2.5                    py27_0  
itsdangerous              0.24                     py27_0  
jbig                      2.1                           0  
jdcal                     1.3                      py27_0  
jedi                      0.9.0                    py27_1  
jinja2                    2.9.4                    py27_0  
jpeg                      9b                            0  
jsonschema                2.5.1                    py27_0  
jupyter                   1.0.0                    py27_3  
jupyter_client            4.4.0                    py27_0  
jupyter_console           5.0.0                    py27_0  
jupyter_contrib_core      0.3.3                    py27_1    conda-forge
jupyter_core              4.2.1                    py27_0  
jupyter_latex_envs        1.4.4                    py27_0    conda-forge
keyring                   9.0                      py27_0    conda-forge
kiwisolver                1.0.1            py27h9856860_0    anaconda
lazy-object-proxy         1.2.2                    py27_0  
libcxx                    4.0.1                h579ed51_0    anaconda
libcxxabi                 4.0.1                hebd6815_0    anaconda
libgfortran               3.0.1                h93005f0_2    anaconda
libiconv                  1.14                          0  
libpng                    1.6.34               he12f830_0    anaconda
libtiff                   4.0.9                h0dac147_0    anaconda
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.22.0           py27h0df46ed_0    anaconda
locket                    0.2.0                    py27_1  
lockfile                  0.12.2                   py27_0    conda-forge
luigi                     2.6.2                    py27_0    conda-forge
lxml                      3.7.2                    py27_0  
lzo                       2.10                 h362108e_2    anaconda
markupsafe                0.23                     py27_2  
matplotlib                2.1.1            py27hb768455_0  
mistune                   0.7.3                    py27_1  
mkl                       2018.0.2                      1    anaconda
mkl-service               1.1.2                    py27_3  
mkl_fft                   1.0.1            py27h917ab60_0    anaconda
mkl_random                1.0.1            py27h78cc56f_0    anaconda
mmtf-python               1.0.2                    py27_0    bioconda
mpmath                    0.19                     py27_1  
msgpack-python            0.4.8                    py27_0  
multipledispatch          0.4.9                    py27_0  
mysql                     0.0.1                     <pip>
mysql-python              1.2.5                    py27_0    coursera
nbconvert                 4.2.0                    py27_0  
nbformat                  4.2.0                    py27_0  
networkx                  1.11                     py27_0  
nltk                      3.2.2                    py27_0  
nose                      1.3.7                    py27_1  
notebook                  4.3.1                    py27_0  
numba                     0.37.0          np114py27h6027bcc_0    anaconda
numexpr                   2.6.4            py27hf375000_0    anaconda
numpy                     1.14.2           py27ha9ae307_1    anaconda
numpydoc                  0.6.0                    py27_0  
odo                       0.5.0                    py27_1  
olefile                   0.45.1                   py27_0    anaconda
openpyxl                  2.4.1                    py27_0  
openssl                   1.0.2o               h26aff7b_0    anaconda
pandas                    0.22.0           py27h0a44026_0    anaconda
pandoc                    2.1.3                         0    conda-forge
partd                     0.3.7                    py27_0  
path.py                   10.0                     py27_0  
pathlib2                  2.2.0                    py27_0  
patsy                     0.4.1                    py27_0  
pep8                      1.7.0                    py27_0  
pexpect                   4.2.1                    py27_0  
pickleshare               0.7.4                    py27_0  
pillow                    4.2.1            py27h2cf1d5f_0    anaconda
pip                       9.0.1                    py27_1  
ply                       3.9                      py27_0  
prompt_toolkit            1.0.9                    py27_0  
psutil                    5.0.1                    py27_0  
ptyprocess                0.5.1                    py27_0  
py                        1.4.32                   py27_0  
pyasn1                    0.1.9                    py27_0  
pyaudio                   0.2.7                    py27_0  
pycosat                   0.6.3            py27h6c51c7e_0    anaconda
pycparser                 2.17                     py27_0  
pycrypto                  2.6.1                    py27_4  
pycurl                    7.43.0                   py27_2  
pyflakes                  1.5.0                    py27_0  
pygments                  2.1.3                    py27_0  
pylint                    1.6.4                    py27_1  
pyopenssl                 16.2.0                   py27_0  
pyparsing                 2.1.4                    py27_0  
pyqt                      5.6.0                    py27_1  
pysam                     0.11.1                   py27_0    bioconda
pysocks                   1.6.7                    py27_0    conda-forge
pytables                  3.4.2            py27ha4551b8_2    anaconda
pytest                    3.0.5                    py27_0  
python                    2.7.13                        0  
python-daemon             2.1.2                    py27_0  
python-dateutil           2.6.0                    py27_0  
python.app                1.2                      py27_4  
pytz                      2016.10                  py27_0  
pywavelets                0.5.2            py27hd99e88a_0    anaconda
pyyaml                    3.12                     py27_0  
pyzmq                     16.0.2                   py27_0  
qt                        5.6.2                         0  
qtawesome                 0.4.3                    py27_0  
qtconsole                 4.2.1                    py27_1  
qtpy                      1.2.1                    py27_0  
readline                  6.2                           2  
redis                     3.2.0                         0  
redis-py                  2.10.5                   py27_0  
reportlab                 3.4.0                    py27_0  
requests                  2.12.4                   py27_0  
rope                      0.9.4                    py27_1  
ruamel_yaml               0.11.14                  py27_1  
samtools                  1.4                           0    bioconda
scandir                   1.4                      py27_0  
scikit-learn              0.19.1           py27h9788993_0    anaconda
scipy                     1.0.1            py27hcaad992_0    anaconda
seaborn                   0.8.1            py27h6bd0ddc_0    anaconda
setuptools                39.0.1                   py27_0    anaconda
simplegeneric             0.8.1                    py27_1  
singledispatch            3.4.0.3                  py27_0  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
snowballstemmer           1.2.1                    py27_0  
sockjs-tornado            1.0.3                    py27_0  
sphinx                    1.5.1                    py27_0  
spyder                    3.1.2                    py27_0  
sqlalchemy                1.1.5                    py27_0  
sqlite                    3.13.0                        0  
ssl_match_hostname        3.4.0.2                  py27_1  
statsmodels               0.8.0            py27h6d68dbf_0    anaconda
subprocess32              3.2.7                    py27_0  
sympy                     1.0                      py27_0  
terminado                 0.6                      py27_0  
tk                        8.5.18                        0  
toolz                     0.8.2                    py27_0  
tornado                   4.4.2                    py27_0  
traitlets                 4.3.1                    py27_0  
unicodecsv                0.14.1                   py27_0  
urllib3                   1.22                     py27_0    conda-forge
wcwidth                   0.1.7                    py27_0  
webencodings              0.5.1                     <pip>
werkzeug                  0.11.15                  py27_0  
wheel                     0.29.0                   py27_0  
widgetsnbextension        1.2.6                    py27_0  
wrapt                     1.10.8                   py27_0  
xlrd                      1.0.0                    py27_0  
xlsxwriter                0.9.6                    py27_0  
xlwings                   0.10.2                   py27_0  
xlwt                      1.2.0                    py27_0  
xz                        5.2.3                h0278029_2    anaconda
yaml                      0.1.6                         0  
youtube-dl                2017.12.31                <pip>
zlib                      1.2.11               hf3cbc9b_2    anaconda

**Comment by nbara** [comment]
I am having the same issue after updating to mpl 2.2 (anaconda, OS X 10.12.6)

**Comment by julia-climacell-co** [comment]
same here

**Comment by WildcatsC** [comment]
Thank you so much for your solution!!!

**Comment by ocefpaf** [comment]
@zzygyx9119 that won't work b/c of https://conda-forge.org/docs/conda-forge_gotchas.html

Try a fresh env and add `conda-forge` on top of `defaults` to get a working environment.
