### ISSUE TITLE
Is it possible to install matplotlib from conda-forge with pyqt4?

### ISSUE THREAD

**Issue by djhoese** [conda-forge/matplotlib-feedstock#164]
It seems like matplotlib from conda-forge now requires pyqt5. My project still uses pyqt 4 (although pyqt 5 is on our TODO list). I can't seem to find a way to install any matplotlib's *and* install pyqt4. Is there any way to do this?

**Comment by djhoese** [comment]
As for my specific issue: I'm trying to create/build an environment with matplotlib, PyQt 4, and gdal. Due to the recent version pinning with HDF5 and GDAL is seems like I can't get a working environment with these three packages.

**Comment by djhoese** [comment]
Small update on this, I am unable to run the following command:

```bash
$ conda create -n sift_2 python=3.6 gdal matplotlib "pyqt<5"
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - gdal
  - matplotlib
  - pyqt[version='<5']
  - python=3.6
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by djhoese** [comment]
@ocefpaf If this isn't something "wrong" with conda-forge packages do you have any suggestions for building my own versions of pyqt or matplotlib or gdal to release the next version of my software (the last one with pyqt4)?

**Comment by ocefpaf** [comment]
> @ocefpaf If this isn't something "wrong" with conda-forge packages 

The problem is that we abandoned `qt` but you are welcomed to:

- get our recipes and re-build them for `qt`;
- try to rebuild the qt4 recipe on conda-forge with latest pinning.

Both are herculean jobs and that is why we are focusing on Qt5 only.

@msarahan does `defaults` provides qt4 and qt5 builds consistent with latest gdal and rasterio? If so @djhoese can use a 100% defatuls solution for thsi problem.

**Comment by djhoese** [comment]
It looks like (with a very simple tests) that I can get everything I need installed for python 3.6 if I don't include matplotlib. If I provide my own custom matplotlib that uses qt4 I *should* (?) be ok, right?

**Comment by ocefpaf** [comment]
> If I provide my own custom matplotlib that uses qt4 I should (?) be ok, right?

In theory yes. conda-forge has plans to split mpl into smaller packages and do not depend directly on `qt`, maybe that is the best solution for you here.

**Comment by djhoese** [comment]
@ocefpaf I copied the conda-forge recipe for matplotlib, changed the patches and dependencies to use pyqt4 instead of pyqt5, built it successfully on a Windows VM, CentOS 7 system, and OSX on my laptop, and uploaded the packages to my local HTTP channel. Building my package that depends on all of these things seems to work now. Thanks for your help.

**Comment by ocefpaf** [comment]
Sorry we cannot afford to maintain both versions here. Note that #157, once ready, should also help your situation there.
