### ISSUE TITLE
Include sample data in conda pkg

### ISSUE THREAD

**Issue by mwcraig** [conda-forge/matplotlib-feedstock#165]
I was talking to @WeatherGod this morning and he asked about including it. Checking on the size...only2MB.

Is there a reason this isn't currently included? Happy to open the PR to fix...

**Comment by ocefpaf** [comment]
We have it here: https://github.com/conda-forge/mpl_sample_data-feedstock

**Comment by WeatherGod** [comment]
it is a total of 2MB, why is it separated?

**Comment by WeatherGod** [comment]
plus, if it needs to be separated, then `get_sample_data()` should be
patched to emit an appropriate message, similar to what is done for hi-res
basemap data.

**Comment by ocefpaf** [comment]
> it is a total of 2MB, why is it separated?

2 MB can be a lot for cloud computing that spin instances on the fly. (Or if you live in places like I do :wink:)

> plus, if it needs to be separated, then `get_sample_data()` should be
patched to emit an appropriate message, similar to what is done for hi-res
basemap data.


PRs welcomed!

**Comment by endolith** [comment]
So you need to run `conda install mpl_sample_data`
