### ISSUE TITLE
missing functools_lru_cache?

### ISSUE THREAD

**Issue by sbillinge** [conda-forge/matplotlib-feedstock#166]
Traceback (most recent call last):                                                                                        File "fitBulkNi.py", line 11, in <module>                                                                                 import matplotlib.pyplot as plt                                                                                       File "/home/sbillinge/miniconda2/envs/py27/lib/python2.7/site-packages/matplotlib/__init__.py", line 128, in <module>     from matplotlib.rcsetup import defaultParams, validate_backend, cycler                                                File "/home/sbillinge/miniconda2/envs/py27/lib/python2.7/site-packages/matplotlib/rcsetup.py", line 29, in <module>       from matplotlib.fontconfig_pattern import parse_fontconfig_pattern                                                    File "/home/sbillinge/miniconda2/envs/py27/lib/python2.7/site-packages/matplotlib/fontconfig_pattern.py", line 32, in <module>                                                                                                                    from backports.functools_lru_cache import lru_cache                                                                 ImportError: No module named functools_lru_cache

**Comment by ocefpaf** [comment]
We will need more information to debug that. How did you installed matplotlib? What is the result of `conda list` for that env?

It works fine BTW and the package is install properly, see https://github.com/conda-forge/matplotlib-feedstock/blob/master/recipe/meta.yaml#L54

Does this work for you?

```shell
conda create --name TEST python=2.7 matplotlib
conda activate TEST
python -c 'import matplotlib.pyplot as plt; print(dir(plt))'
```

**Comment by sbillinge** [comment]
Sorry, yes, matplotlib was installed initially from default channel on conda, but then updated through conda-forge channel.

here is the ``conda list``:
backports                 1.0                      py27_0    defaults
backports-abc             0.5                       <pip>
backports.functools_lru_cache 1.5                        py_1    conda-forge
backports.shutil-get-terminal-size 1.0.0                     <pip>
backports.ssl-match-hostname 3.5.0.1                   <pip>
backports_abc             0.5                      py27_0    defaults
bleach                    1.5.0                    py27_0    defaults
boost                     1.61.0                   py27_0    defaults
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.6                        5    conda-forge
certifi                   2016.2.28                py27_0    defaults
configparser              3.5.0                    py27_0    defaults
cycler                    0.10.0                   py27_0    defaults
dbus                      1.10.20                       0    defaults
decorator                 4.1.2                    py27_0    defaults
diffpy-cmi                2.1                  hfb420b8_0    diffpy
diffpy.srfit              1.3              py27h278c996_0    diffpy
diffpy.srreal             1.2                      py27_0    diffpy
diffpy.structure          1.3.5                    py27_0    diffpy
diffpy.utils              1.2.2                    py27_0    diffpy
entrypoints               0.2.3                    py27_0    defaults
enum34                    1.1.6                    py27_0    defaults
expat                     2.1.0                         0    defaults
fontconfig                2.12.1                        3    defaults
freetype                  2.7                           0    conda-forge
functools32               3.2.3.2                  py27_0    defaults
futures                   3.1.1                    py27_0    defaults
get_terminal_size         1.0.0                    py27_0    defaults
gettext                   0.19.8.1                      0    conda-forge
glib                      2.51.0                        0    conda-forge
gsl                       2.2.1                         0    defaults
gst-plugins-base          1.8.0                         0    defaults
gstreamer                 1.8.0                         0    defaults
html5lib                  0.9999999                py27_0    defaults
icu                       58.1                          0    conda-forge
ipykernel                 4.6.1                    py27_0    defaults
ipyparallel               6.0.2                    py27_0    defaults
ipython                   5.3.0                    py27_0    defaults
ipython-genutils          0.2.0                     <pip>
ipython_genutils          0.2.0                    py27_0    defaults
ipywidgets                6.0.0                    py27_0    defaults
jinja2                    2.9.6                    py27_0    defaults
jpeg                      9b                            0    defaults
jsonschema                2.6.0                    py27_0    defaults
jupyter                   1.0.0                    py27_3    defaults
jupyter-client            5.1.0                     <pip>
jupyter-console           5.2.0                     <pip>
jupyter-core              4.3.0                     <pip>
jupyter_client            5.1.0                    py27_0    defaults
jupyter_console           5.2.0                    py27_0    defaults
jupyter_core              4.3.0                    py27_0    defaults
libdiffpy                 1.3.4                         0    diffpy
libffi                    3.2.1                         1    defaults
libgcc                    5.2.0                         0    defaults
libgfortran               3.0.0                         1    defaults
libiconv                  1.14                          0    defaults
libobjcryst               2017.1.1                      0    diffpy
libpng                    1.6.30                        1    defaults
libsodium                 1.0.10                        0    defaults
libxcb                    1.12                          1    defaults
libxml2                   2.9.4                         4    conda-forge
libxslt                   1.1.29                        0    defaults
lxml                      3.8.0                    py27_0    defaults
markupsafe                1.0                      py27_0    defaults
matplotlib                2.1.1                    py27_0    conda-forge
mistune                   0.7.4                    py27_0    defaults
mkl                       2017.0.3                      0    defaults
nbconvert                 5.2.1                    py27_0    defaults
nbformat                  4.4.0                    py27_0    defaults
ncurses                   5.9                          10    conda-forge
notebook                  5.0.0                    py27_0    defaults
numpy                     1.13.1                   py27_0    defaults
openssl                   1.0.2l                        0    defaults
pandocfilters             1.4.2                    py27_0    defaults
path.py                   10.3.1                   py27_0    defaults
pathlib2                  2.3.0                    py27_0    defaults
pcre                      8.39                          1    defaults
periodictable             1.5.0                    py27_0    diffpy
pexpect                   4.2.1                    py27_0    defaults
pickleshare               0.7.4                    py27_0    defaults
pip                       9.0.1                    py27_1    defaults
pixman                    0.34.0                        0    defaults
prompt-toolkit            1.0.15                    <pip>
prompt_toolkit            1.0.15                   py27_0    defaults
ptyprocess                0.5.2                    py27_0    defaults
pycairo                   1.10.0                   py27_0    defaults
pycifrw                   4.3                      py27_0    diffpy
pygments                  2.2.0                    py27_0    defaults
pyobjcryst                2.0.2                    py27_2    diffpy
pyparsing                 2.2.0                    py27_0    defaults
pyqt                      5.6.0                    py27_2    defaults
python                    2.7.14                        2    conda-forge
python-dateutil           2.6.1                    py27_0    defaults
pytz                      2017.2                   py27_0    defaults
pyzmq                     16.0.2                   py27_0    defaults
qt                        5.6.2                         6    conda-forge
qtconsole                 4.3.1                    py27_0    defaults
readline                  6.2                           2    defaults
scandir                   1.5                      py27_0    defaults
scipy                     0.19.1              np113py27_0    defaults
setuptools                36.4.0                   py27_1    defaults
simplegeneric             0.8.1                    py27_1    defaults
singledispatch            3.4.0.3                  py27_0    defaults
sip                       4.18                     py27_0    defaults
six                       1.10.0                   py27_0    defaults
sqlite                    3.13.0                        0    defaults
srfit-sasview             3.1.2                    py27_0    diffpy
ssl_match_hostname        3.5.0.1                  py27_0    defaults
subprocess32              3.2.7                    py27_0    defaults
terminado                 0.6                      py27_0    defaults
testpath                  0.3.1                    py27_0    defaults
tk                        8.5.18                        0    defaults
tornado                   4.5.2                    py27_0    defaults
traitlets                 4.3.2                    py27_0    defaults
wcwidth                   0.1.7                    py27_0    defaults
wheel                     0.29.0                   py27_0    defaults
widgetsnbextension        3.0.2                    py27_0    defaults
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                         0    conda-forge
zeromq                    4.1.5                         0    defaults
zlib                      1.2.11                        0    defaults

**Comment by ocefpaf** [comment]
> Sorry, yes, matplotlib was installed initially from default channel on conda, but then updated through conda-forge channel.

That rarely works and as you can see you got a bad mix of `conda-forge` and `defaults` packages. Please see https://conda-forge.org/docs/conda-forge_gotchas.html for more info.

**Comment by sbillinge** [comment]
gotcha, I will do a clean build and see what happens.  In the mean-time, here is the result of the ``TEST``.  Unfortunately also not so great...
sbillinge@LAPTOP-FU6OME5O:~$ source activate TEST
discarding /home/sbillinge/miniconda2/bin from PATH
prepending /home/sbillinge/miniconda2/envs/TEST/bin to PATH
(TEST)sbillinge@LAPTOP-FU6OME5O:~$ python -c 'import matplotlib.pyplot as plt; print(dir(plt))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sbillinge/miniconda2/envs/TEST/lib/python2.7/site-packages/matplotlib/__init__.py", line 128, in <module>
    from matplotlib.rcsetup import defaultParams, validate_backend, cycler
  File "/home/sbillinge/miniconda2/envs/TEST/lib/python2.7/site-packages/matplotlib/rcsetup.py", line 29, in <module>
    from matplotlib.fontconfig_pattern import parse_fontconfig_pattern
  File "/home/sbillinge/miniconda2/envs/TEST/lib/python2.7/site-packages/matplotlib/fontconfig_pattern.py", line 26, in <module>
    from pyparsing import (Literal, ZeroOrMore, Optional, Regex, StringEnd,
ImportError: No module named pyparsing

**Comment by ocefpaf** [comment]
Can you post your `.condarc`? (`cat ~/.condarc` should do it.)

**Comment by sbillinge** [comment]
sure:
```
channels:
  - conda-forge
  - defaults
  - diffpy
```

**Comment by ocefpaf** [comment]
Can you also post the `conda list` for the `TEST` env?

**Comment by sbillinge** [comment]
sure, here it is:
```
# packages in environment at /home/sbillinge/miniconda2/envs/TEST:
#
Could not extract name and version from: 'Package        Version'
Could not extract name and version from: '-------------- -----------'
Could not extract name and version from: 'backports-abc  0.5'
Could not extract name and version from: 'certifi        2018.4.16'
Could not extract name and version from: 'functools32    3.2.3.post2'
Could not extract name and version from: 'futures        3.2.0'
Could not extract name and version from: 'matplotlib     2.1.1'
Could not extract name and version from: 'numpy          1.13.1'
Could not extract name and version from: 'pip            18.0'
Could not extract name and version from: 'setuptools     40.0.0'
Could not extract name and version from: 'singledispatch 3.4.0.3'
Could not extract name and version from: 'six            1.11.0'
Could not extract name and version from: 'subprocess32   3.5.2'
Could not extract name and version from: 'tornado        5.1'
Could not extract name and version from: 'wheel          0.31.1'
backports                 1.0                      py27_1    conda-forge
backports.functools_lru_cache 1.5                        py_1    conda-forge
backports_abc             0.5                      py27_0    defaults
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py27_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.11.0                        0    conda-forge
expat                     2.2.5                         0    conda-forge
fontconfig                2.12.1                        5    conda-forge
freetype                  2.7                           2    conda-forge
functools32               3.2.3.2                  py27_2    conda-forge
futures                   3.2.0                    py27_0    conda-forge
gettext                   0.19.8.1                      0    conda-forge
glib                      2.53.5                        1    conda-forge
gst-plugins-base          1.8.0                         0    defaults
gstreamer                 1.8.0                         1    conda-forge
icu                       58.2                          0    conda-forge
jpeg                      9b                            2    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    5.2.0                         0    defaults
libiconv                  1.14                          4    conda-forge
libpng                    1.6.30                        1    defaults
libxcb                    1.13                          0    conda-forge
libxml2                   2.9.5                         1    conda-forge
matplotlib                2.1.1                    py27_0    conda-forge
mkl                       2017.0.3                      0    defaults
ncurses                   5.9                          10    conda-forge
numpy                     1.13.1                   py27_0    defaults
openssl                   1.0.2o                        0    conda-forge
pcre                      8.41                          1    conda-forge
pip                       18.0                     py27_0    conda-forge
pyparsing                 2.2.0                      py_1    conda-forge
pyqt                      5.6.0                    py27_5    conda-forge
python                    2.7.14                        2    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
qt                        5.6.2                         6    conda-forge
readline                  6.2                           2    defaults
setuptools                40.0.0                   py27_0    conda-forge
singledispatch            3.4.0.3                  py27_0    defaults
sip                       4.18                     py27_1    conda-forge
six                       1.11.0                   py27_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
subprocess32              3.5.2                    py27_0    conda-forge
tk                        8.5.19                        2    conda-forge
tornado                   5.1                      py27_0    conda-forge
wheel                     0.31.1                   py27_0    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11                        0    defaults
```

**Comment by ocefpaf** [comment]
I see

`pyparsing                 2.2.0                      py_1    conda-forge`

there, so I guess you are having some sort of path issue with your env activation :-/

**Comment by sbillinge** [comment]
I am using ubuntu App on Windows 10, so could be related to that?   

I am ok punting on this for now in any case as I want to move the ``diffpy-cmi`` "windows" release that I was working on to our Py3 version.  Then if there are installation problems I will actually be debugging the version I want for the long term....

**Comment by sbillinge** [comment]
but if you think it is a matplotlib packaging issue and you want to get to the bottom of it, I am also happy to keep giving you feedback.

**Comment by ocefpaf** [comment]
> I am using ubuntu App on Windows 10, so could be related to that?

Probably not.

What do you get for `which python` there?

> but if you think it is a matplotlib packaging issue 

Definitely not. As you can see above everything is installed properly.
