### ISSUE TITLE
Package license PSF or GPL when depending on PyQt5

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/matplotlib-feedstock#171]
I would like to have a focused discussion on whether or not the matplotlib package that **depends** on PyQt5  should be listed as a GPL package.

I would like to note that 
  - Qt5 is LGPL
  - PyQt5 is GPL <- (that dropped L is important)
  - PySide2 is LGPL  (sigh.... I forgot the first L in my original post)
  - Matplotlib is BSD by choice  https://matplotlib.org/devel/license.html#license-discussion

This applies to whatever package (whether it be named `matplotlib` or `matplotlib-pyqt`) has the lines
```yaml
requirements:
  run:
```
https://github.com/conda-forge/matplotlib-feedstock/blob/cd867cd9e17930ec24097b0f569c7890d8a07b4f/recipe/meta.yaml#L61
and claims to be PSF
https://github.com/conda-forge/matplotlib-feedstock/blob/cd867cd9e17930ec24097b0f569c7890d8a07b4f/recipe/meta.yaml#L88

By having this dependency, and along with it the associated patches to make the default backend PyQt5, is conda-forge creating a **derivative work**, which would mean that the resulting work needs to be covered by GPL?

While the interpreted code that calls `PyQt5` is provided to the user, and can be modified to not import PyQt5 through various means, a standard user may be trying to download matplotlib through conda-forge, and using a standard `import` command in python, it is possible for them to create work that is **dynamically linked** to a GPL'ed piece of software. This has very different implications than work that is covered and advertised by the PSF.

The copyleft nature of GPL is particularly important to note. This has vastly different implications for anybody that shares code than simply needing to include an additional `LICENSE` file.

I can't speak for the original packagers, but I would prefer a package that aligns more closely with the desires of the orignal library developers.

Personally, I think that if you list a GPL package as a dependency, and the default execution path will cause the GPL code to be executed, then your package should be listed as GPL. 

In fact, the following commands will do just that:
```bash
conda create --name mpl_clean -y
conda activate mpl_clean
conda install matplotlib -y
python
```
```python
from matplotlib import pyplot
pyplot.plot(1, 1)
pyplot.show()
```
In typing in these lines of code, as a user, I never explicitly agreed to any terms that approach the language of GPL. Matplotlib advertised itself as PSF.

What should people that need Qt do?

1. Ship a package that will not automatically install a Qt backend. This is what matplotlib does on pypi:
```bash
➤ pip freeze matplotlib                                                                            (mpl) 
certifi==2018.8.13
cycler==0.10.0
kiwisolver==1.0.1
matplotlib==2.2.3
numpy==1.14.3
pyparsing==2.2.0
python-dateutil==2.7.3
pytz==2018.5
six==1.11.0
tornado==5.1
```
2. Provide a version of PyQt with a license they purchased from Riverbank
3. Don't use PyQt, use PySide (easier said than done these days).
4. Distribute their final product under the GPL and bundle PyQt as a dependency.

**Comment by andreped** [comment]
@hmaarrfk This is a very interesting and valid point, and I am very interesting in knowing if you converged to some conclusion.
