### ISSUE TITLE
How to depend on matplotlib-base?

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/matplotlib-feedstock#179]
It might be advantageous to depend on `matplotlib-base`, but unfortunately, it only exists for `3.0.0`.

For example, `scikit-image` would like to depend on `matplotlib` `2.0.0`, but adding the dependency on `matplotlib-base` effectively increases the minimum version to `3`

Any thoughts?

**Comment by ocefpaf** [comment]
There is a significant effort to get the split recipe working (and we got it wrong many times BTW :smile:). However, if you want to send a PR to a branch for mpl 2.0 I will gladly review it.

Although pretty soon everything will support mpl 3.0, so I'm not sure if it is worth the effort.

**Comment by ocefpaf** [comment]
> Is it smart to remove a dependency for an older package?

It is a discontinuous (and confusing) change. But the effort to port this to mpl 2.0 is not something I can afford to do now. (Day job is calling...)

**Comment by hmaarrfk** [comment]
Yeah, I found the bug (and workaround) in conda-forge that was stopping me
from creating and uploading my own packages.

I think this is more a nice to have than a must have anyway.

I think we can focus our time on more important things, I was  mostly
wondering if somebody found the magical yaml lines to achieve this quickly.

**Comment by ocefpaf** [comment]
We forgot to close this one. We have `2.2.3` with the same split-name scheme for a while now thanks to @hmaarrfk!

**Comment by hmaarrfk** [comment]
I think somebody else did the effort for 2.2.3

**Comment by ocefpaf** [comment]
> I think somebody else did the effort for 2.2.3

Indeed. The credits go to @duncanmmacleod in https://github.com/conda-forge/matplotlib-feedstock/pull/198
