### ISSUE TITLE
When will matplotlib dependencies support Python 3.7

### ISSUE THREAD

**Issue by enlighter** [conda-forge/matplotlib-feedstock#193]
Issue: Currently this package has dependencies listed as:
`dependencies:
    matplotlib-base 3.0.2 py36h20b835b_1
    pyqt >=5.6.0,<5.7.0a0
    python >=3.6,<3.7.0a0`

However, matplotlib 3.0.2 has python 3.7 wheels in PyPi. So when will this package start supporting Python 3.7

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ocefpaf** [comment]
Works for me,

```shell
conda create --name TEST python=3.7 matplotlib
```

I guess you may be trying to install another package that is forcing a downgrade oe something. BTW, we cannot debug your try b/c you did not fill the `conda list` and `conda info` in the issue.

**Comment by enlighter** [comment]
@ocefpaf I have updated `conda list` and `conda info` sections.

Curiously, `conda update --all` doesn't update the environment to python 3.7, but doing `conda install "python>=3.7"` works.
