### ISSUE TITLE
Old versions of matplotlib no longer labeled as main

### ISSUE THREAD

**Issue by jeremyjliu** [conda-forge/matplotlib-feedstock#205]
Background: On the anaconda conda-forge channel, older (but I believe still working) versions of matplotlib are no longer labeled as `main`. For example, linux-64/matplotlib-2.0.2-py27_2.tar.bz2 only has the `cf201901` label.

Question: I believe without the `main` label, these versions are not installable from `conda build` or `conda create`. Is this change intended? Is there a way to utilize these older versions still?

**Comment by ocefpaf** [comment]
```
conda create --name TEST --channel conda-forge/label/cf201901 matplotlib=1
```
