### ISSUE TITLE
Build for aarch64

### ISSUE THREAD

**Issue by hadim** [conda-forge/matplotlib-feedstock#221]
Do you guys think it's possible to get an aarch64 build for matplotlib. Looking at https://conda-forge.org/status/, it seems that there is a couple of blocking packages upstream such as pyqt, qt, nss.

I don't really understand how far/hard would that be to get it to build.

Let me know your thoughts.

ping @conda-forge/matplotlib

**Comment by dopplershift** [comment]
#215 should be adding them, but I’m not sure what’s going on. Any ideas @conda-forge/core?

**Comment by hadim** [comment]
wow sorry for missing this PR. Great if we are close to getting the build!

**Comment by dopplershift** [comment]
Closed by #223 .
