### ISSUE TITLE
Building devel packages

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/matplotlib-feedstock#227]
So we have the `devel` branch for building development packages, like the rc's.

For some reason they're uploading to the `main` label, and I'm not sure why. There's a listing for channels in `conda-forge.yaml`.

Can someone from @conda-forge/core fix the label for those packages and point out what we're doing wrong here?

**Comment by dopplershift** [comment]
Ah, ok, found the problem. The alternate channel needs to be listed in `recipe/conda_build_config.yaml`, not `conda-forge.yml`.

**Comment by isuruf** [comment]
See https://github.com/conda-forge/conda-smithy/issues/996

**Comment by dopplershift** [comment]
Personally, I'm not too concerned with the generated README for alternate branches (i.e. not master or default in anyway). Is there a reason I should be?

**Comment by isuruf** [comment]
We should fix that and remove the setting in `conda-forge.yml`, so that there's no confusion

**Comment by dopplershift** [comment]
Fair enough. FYI, there are 5 remaining packages that need moving now that they've been uploaded.

**Comment by dopplershift** [comment]
@isuruf Can you also fix up the 3.2.0rc2 packages here: https://anaconda.org/conda-forge/matplotlib-base/files ?

**Comment by dopplershift** [comment]
Fixed by #228 .
