### ISSUE TITLE
built with ICU 67

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/matplotlib-feedstock#255]
It seems that matplotlib was built with ICU 67 recently, but qt hasn't been rebuilt yet so the bot should not have opened the PR yet. Also of interest is that the build didn't fail (logs [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=181914&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412&l=2955) as we'd expect. I'm not certain what is going on there, it seems to have pulled the older `matplotlib-base` build rather than the local build. This caused conda to pull in the older ICU which didn't generate a conflict.

**Comment by CJ-Wright** [comment]
The short term fix for this is to remove the migration file [here](https://github.com/conda-forge/matplotlib-feedstock/blob/master/.ci_support/migrations/icu67.yaml) in the new version bump PR and most likely mark the previous build as broken. I can then put in a fix to the bot to properly track the pyqt dep and reset it so mpl will get the needed PR when qt has been upgraded.

**Comment by dopplershift** [comment]
Latest builds for 3.3.2 built with icu 67.1. Is that a problem or can we close this out?
