### ISSUE TITLE
conda-forge matplotlib install error

### ISSUE THREAD

**Issue by parthe** [conda-forge/matplotlib-feedstock#288]
Installed matplotlib using

```conda install -c conda-forge matplotlib```

This matplotlib worked when I opened ipython in the terminal

However when using with the ipython inside **_Spyder_**, this gave the following error

```**ImportError**: DLL load failed while importing ft2font: The specified module could not be found.```

```conda install matplotlib=3.3``` resolved this issue.

**Comment by isuruf** [comment]
We ask for details in the issue template and you have ignored it. Please create a new issue with the details we have asked for in https://github.com/conda-forge/matplotlib-feedstock
