### ISSUE TITLE
[Bug]: macOS: PyPy 3.8 (v7.3.9) threading get_native_id Broken

### ISSUE THREAD

**Issue by ax3l** [conda-forge/matplotlib-feedstock#332]
This is cross-posting the upstream issues in for tracking in conda-forge, where it affects my CI runners in https://github.com/conda-forge/impactx-feedstock/pull/8
- PyPy: https://foss.heptapod.net/pypy/pypy/-/issues/3764
- matplotlib: https://github.com/matplotlib/matplotlib/issues/24094

**Comment by ax3l** [comment]
Matplotlib patch in https://github.com/matplotlib/matplotlib/pull/24178

**Comment by dopplershift** [comment]
This should be fixed with the release of 3.6.2. #338  Feel free to re-open if you find that not to be the case.

**Comment by ax3l** [comment]
Thanks a lot! :)
