### ISSUE TITLE
Further dependency problems

### ISSUE THREAD

**Issue by pelson** [conda-forge/matplotlib-feedstock#36]
```
$ conda create nomkl ggplot python=3.4 -n ggplot -c conda-forge -c defaults
Fetching package metadata ...........
Solving package specifications ............

Package plan for installation in environment /data/local/itpe/miniconda/envs/ggplot:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgfortran-3.0.0          |                1         281 KB  defaults
    libiconv-1.14              |                2         1.3 MB  conda-forge
    nomkl-1.0                  |                0          402 B  defaults
    openssl-1.0.2h             |                1         3.2 MB  defaults
    readline-6.2               |                2         606 KB  defaults
    sqlite-3.13.0              |                1         4.9 MB  conda-forge
    xz-5.2.2                   |                0         853 KB  conda-forge
    zlib-1.2.8                 |                3          87 KB  conda-forge
    libpng-1.6.23              |                0         296 KB  conda-forge
    openblas-0.2.14            |                4         3.6 MB  defaults
    python-3.4.4               |                5        15.3 MB  defaults
    freetype-2.6.3             |                1         2.8 MB  conda-forge
    numpy-1.11.1               |     py34_nomkl_0         6.1 MB  defaults
    pyparsing-2.1.4            |           py34_0          72 KB  defaults
    pytz-2016.4                |           py34_0         177 KB  defaults
    setuptools-23.0.0          |           py34_0         461 KB  defaults
    sip-4.18                   |           py34_0         238 KB  conda-forge
    six-1.10.0                 |           py34_0          18 KB  conda-forge
    brewer2mpl-1.4.1           |           py34_1          24 KB  conda-forge
    cycler-0.10.0              |           py34_0          13 KB  conda-forge
    fontconfig-2.11.1          |                3         874 KB  conda-forge
    patsy-0.4.1                |           py34_0         372 KB  defaults
    python-dateutil-2.5.3      |           py34_0         238 KB  defaults
    scipy-0.17.1               |np111py34_nomkl_1        29.7 MB  defaults
    pandas-0.18.1              |      np111py34_0        15.4 MB  conda-forge
    qt-4.8.7                   |                3        34.1 MB  defaults
    pyqt-4.11.4                |           py34_3         3.4 MB  defaults
    statsmodels-0.6.1          |      np111py34_1         5.2 MB  defaults
    matplotlib-1.5.1           |      np111py34_4         6.7 MB  conda-forge
    ggplot-0.9.4               |           py34_0         1.4 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       137.6 MB

The following NEW packages will be INSTALLED:

    brewer2mpl:      1.4.1-py34_1             conda-forge
    cycler:          0.10.0-py34_0            conda-forge
    fontconfig:      2.11.1-3                 conda-forge
    freetype:        2.6.3-1                  conda-forge
    ggplot:          0.9.4-py34_0             conda-forge
    libgfortran:     3.0.0-1                  defaults   
    libiconv:        1.14-2                   conda-forge
    libpng:          1.6.23-0                 conda-forge
    libxml2:         2.9.2-0                  defaults   
    matplotlib:      1.5.1-np111py34_4        conda-forge
    nomkl:           1.0-0                    defaults   
    numpy:           1.11.1-py34_nomkl_0      defaults    [nomkl]
    openblas:        0.2.14-4                 defaults   
    openssl:         1.0.2h-1                 defaults   
    pandas:          0.18.1-np111py34_0       conda-forge
    patsy:           0.4.1-py34_0             defaults   
    pyparsing:       2.1.4-py34_0             defaults   
    pyqt:            4.11.4-py34_3            defaults   
    python:          3.4.4-5                  defaults   
    python-dateutil: 2.5.3-py34_0             defaults   
    pytz:            2016.4-py34_0            defaults   
    qt:              4.8.7-3                  defaults   
    readline:        6.2-2                    defaults   
    scipy:           0.17.1-np111py34_nomkl_1 defaults    [nomkl]
    setuptools:      23.0.0-py34_0            defaults   
    sip:             4.18-py34_0              conda-forge
    six:             1.10.0-py34_0            conda-forge
    sqlite:          3.13.0-1                 conda-forge
    statsmodels:     0.6.1-np111py34_1        defaults   
    tk:              8.5.18-0                 defaults   
    xz:              5.2.2-0                  conda-forge
    zlib:            1.2.8-3                  conda-forge
```

```
python -c "import matplotlib.backends.backend_qt4agg"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/local/itpe/miniconda/envs/ggplot/lib/python3.4/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/data/local/itpe/miniconda/envs/ggplot/lib/python3.4/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import QtCore
  File "/data/local/itpe/miniconda/envs/ggplot/lib/python3.4/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/data/local/itpe/miniconda/envs/ggplot/lib/python3.4/site-packages/matplotlib/backends/qt_compat.py", line 124, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory
```

This is the same issue as seen in https://github.com/conda-forge/ggplot-feedstock/pull/2.

**Comment by pelson** [comment]
```
lib/libQtGui.so                                      
	linux-vdso.so.1 =>  (0x00007ffd01fdb000)
	libQtCore.so.4 => /data/local/itpe/miniconda/envs/ggplot/lib/./libQtCore.so.4 (0x00007f15d2323000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f15d20dd000)
	libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007f15d1ed9000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f15d1bc2000)
	libpng16.so.16 => /data/local/itpe/miniconda/envs/ggplot/lib/./libpng16.so.16 (0x00007f15d1981000)
	libz.so.1 => /data/local/itpe/miniconda/envs/ggplot/lib/./libz.so.1 (0x00007f15d1766000)
	libfreetype.so.6 => /data/local/itpe/miniconda/envs/ggplot/lib/./libfreetype.so.6 (0x00007f15d14cb000)
	libgobject-2.0.so.0 => /lib64/libgobject-2.0.so.0 (0x00007f15d127e000)
	libSM.so.6 => /usr/lib64/libSM.so.6 (0x00007f15d1076000)
	libICE.so.6 => /usr/lib64/libICE.so.6 (0x00007f15d0e5a000)
	libXrender.so.1 => /usr/lib64/libXrender.so.1 (0x00007f15d0c50000)
	libfontconfig.so.1 => /data/local/itpe/miniconda/envs/ggplot/lib/./libfontconfig.so.1 (0x00007f15d0a14000)
	libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007f15d0802000)
	libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007f15d04c4000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f15d01be000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f15cff3a000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f15cfd23000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f15cf98f000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f15cf78b000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f15cf582000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003670800000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f15cf37e000)
	libxml2.so.2 => /data/local/itpe/miniconda/envs/ggplot/lib/././libxml2.so.2 (0x00007f15cf023000)
	libicui18n.so.56 => not found
	libicuuc.so.56 => not found
	libicudata.so.56 => not found
	liblzma.so.5 => /data/local/itpe/miniconda/envs/ggplot/lib/././liblzma.so.5 (0x00007f15cedfd000)
	libiconv.so.2 => /data/local/itpe/miniconda/envs/ggplot/lib/././libiconv.so.2 (0x00007f15ceb0f000)
	libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007f15ce8ef000)
	libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f15ce6ec000)
```

@msarahan - I believe the qt package depends upon `icu` - would it be possible to update the defaults channel to reflect this?

**Comment by ocefpaf** [comment]
> @msarahan - I believe the qt package depends upon icu - would it be possible to update the defaults channel to reflect this?

It might be a `qt` dependency that brings `icu` at build time and the linking happens. If that is the case it is this dependency that needs fixing and not `qt `. (I believe `icu` is an optional dependency for `qt`)

**Comment by msarahan** [comment]
I'll look into it.  In the meantime, can we please talk about building qt for conda-forge somehow?  This arrangement of asking defaults to update some package to make conda-forge work is not really tenable.  Conda-forge needs to be able to fix itself.

**Comment by ocefpaf** [comment]
> I'll look into it. In the meantime, can we please talk about building qt for conda-forge somehow?

\+ :100: 

I would be OK if someone builds `qt` in a "trusted" machine with a recipe in a feedstock and uploads it to conda-forge. (I already suggested that a couple of times but never got any feedback.)

**Comment by msarahan** [comment]
That is exactly what I had in mind.  I know that @jakirkham has strong opinions against this approach, but surely it is better than depending on defaults to fix/update packages?

**Comment by pelson** [comment]
To be clear, we have found a bug with defaults. Sure, I accept that conda-forge would be in a much healthier place if it didn't have `defaults` dependencies, but *even* if we were in that position, we would still be finding `defaults` bugs and raising them. Maybe your point is that if we are able to build ourselves, we wouldn't care if they got fixed or not on `defaults`?

**Comment by msarahan** [comment]
Yes.  I certainly appreciate people raising issues where bugs exist.  It may or may not be a bug though - if our stack is still on icu 54 or whatever here (which I think it is), then our stuff is working, and updating qt may then require updating other packages.  I don't think it's a bug.  I think it's an inconsistency in the stacks.  Any bug might be a lack of pinning.

I think the likelihood of both conda-forge's stack and defaults' stack being completely in sync is pretty low at any given time.  Unless they are in sync, there will be problems like this.  Conda-forge is better served by getting the ability to maintain internal consistency.  This might make the channels less inter-mixable, but at worst, people may need to be more careful about pinning dependencies, and the solver is going to have to catch things like this

**Comment by jakirkham** [comment]
So, can you help me understanding something, @msarahan. Why couldn't Anaconda build workers be used for this?

**Comment by msarahan** [comment]
There are no workers to dedicate to this.  If anyone wants to figure out how to add workers, the site machinery itself should still work.  However, there will be little to no support for any issues encountered.  That team has been mostly reassigned to other projects. =(

We'd probably encounter issues such as log lengths getting too long.  I think that was an unaddressed issue.

If anyone wants to set up CI with jenkins or GitLab or whatever - go for it.  I'd be thrilled.  I can't do that.  That's a lot of work, though.  For Linux, the docker images are glorious.  For win, we have my vagrant start - that would need development and testing.  For mac, ???  And then - how to connect with github?  There is https://wiki.jenkins-ci.org/display/JENKINS/GitHub+Plugin - but the integration needs to be very good if it is going to replace the existing CIs in any way.

I just think you're getting hung up on human-in-the-loop a bit too much.  This is about practicality, and while I agree that human-in-the-loop is not desirable, it may be (temporarily) necessary in the absence of alternatives

**Comment by ccordoba12** [comment]
I don't understand how Qt4 ended up with a dependency on ICU, but I'll fix that for our next build.

**Comment by jakirkham** [comment]
Thanks @ccordoba12 I saw that before somewhere else and was trying to understand why.

**Comment by ocefpaf** [comment]
@pelson there are other reasons why we may want to maintain our own `qt`. See https://github.com/conda-forge/geopandas-feedstock/issues/9#issuecomment-229987853

**Comment by zym1010** [comment]
@pelson  Thanks for the detailed explanation! So what should I do now to fix this? Explicitly specify `icu` when creating my environment?

**Comment by pelson** [comment]
> @pelson Thanks for the detailed explanation! So what should I do now to fix this? Explicitly specify icu when creating my environment?

Installing `icu` should solve the problem, yes. It will need to be version `56` by the looks of it, but I think that is the latest one on `defaults` anyway, so just `conda install icu` should do it. 👍

**Comment by pelson** [comment]
@ocefpaf - we have an option to mitigate this situation for mpl...
We could cease using qt as the default matplotlib backend...

**Comment by jakirkham** [comment]
I believe`qt` is offered so the user has *some* option for a backend. Though there is no reason that the option must be `qt`, right? Given the stability of the `notebook`/`nbagg` and `webagg` backends (and there web friendliness), does it still make sense to ship a backend like `qt` with `matplotlib`? These are honest questions.

**Comment by pelson** [comment]
Agreed. I raised https://github.com/conda/conda/issues/2984 for a similar reason. Essentially, some usecases simply don't need any backend with matplotlib.

**Comment by ocefpaf** [comment]
> @ocefpaf - we have an option to mitigate this situation for mpl...
> We could cease using qt as the default matplotlib backend...

`tk` was the default option some time ago, right? Although I believe that 99.9% of the people prefer `qt`.

:+1: from me.

**Comment by pelson** [comment]
> Although I believe that 99.9% of the people prefer qt.

100% of the people who get tripped up by this will prefer to have *anything* that worked. 😄

**Comment by ocefpaf** [comment]
> Essentially, some use cases simply don't need any backend with matplotlib.

Ah, but that is another beast #2 :smile: that would partially solve this issue and make it easy for lots of projects to use matplotlib in their projects.

> 100% of the people who get tripped up by this will prefer to have *anything* that worked. 😄 

Oh yes. Don't get me wrong. I am :+1: to use anything rather than `Qt`.

**Comment by pelson** [comment]
Looks like this may have been solved. https://github.com/conda-forge/matplotlib-feedstock/pull/42#issuecomment-234218228 🎉

**Comment by bsipocz** [comment]
I'm seeing this same issue when trying to build packages for python3.6:
https://travis-ci.org/astropy/conda-channel-astropy/jobs/190264269#L2853

Could anyone point me to a solution/workaround?

**Comment by ocefpaf** [comment]
@bsipocz try to pin`icu` to `56` in your CI. The issue you are experiencing will go away once conda-forge builds `Qt` for `OS X`.

**Comment by bsipocz** [comment]
@ocefpaf - actually the failing build is on linux, the osx works perfectly. By pinning ``icu`` you mean ``libicu-dev`` from the apt packages?

**Comment by ocefpaf** [comment]
> @ocefpaf - actually the failing build is on linux, the osx works perfectly.

Interesting. I never experienced that on Linux. I will take a look at your dependency stack and configuration later, but pinning `icu` should solved.

> By pinning ``icu`` you mean ``libicu-dev`` from the apt packages?

No. You should not rely on your Linux package manager for `conda`/`conda-forge` dependencies. I do mean the `conda` installed `icu`. As you can see [here](https://travis-ci.org/astropy/conda-channel-astropy/jobs/190264269#L1270) you are getting version `54.1` and conda-forge packages are pinned to `icu 65.*`. So the problem there is that `conda` is mixing packages from `defaults`, with `icu 54.1` and `conda-forge` packages with `icu 56`.
