### ISSUE TITLE
ImportError in clean environment

### ISSUE THREAD

**Issue by astrofrog** [conda-forge/matplotlib-feedstock#39]
I created a new installation of Miniconda on MacOS X 10.11 and did:

```
$ conda create -n debug -c conda-forge python=3.5 matplotlib nomkl
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /Users/tom/miniconda3/envs/debug:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    nomkl-1.0                  |                0          486 B
    openssl-1.0.2h             |                1         3.0 MB
    tk-8.5.19                  |                0         2.0 MB
    zlib-1.2.8                 |                3          90 KB
    libpng-1.6.23              |                0         319 KB
    python-3.5.2               |                0        21.8 MB
    freetype-2.6.3             |                1         782 KB
    numpy-1.11.1               |     py35_nomkl_0         2.7 MB
    pyparsing-2.1.4            |           py35_0          72 KB
    pytz-2016.4                |           py35_0         177 KB
    setuptools-23.0.0          |           py35_0         460 KB
    six-1.10.0                 |           py35_0          18 KB
    cycler-0.10.0              |           py35_0          13 KB
    pip-8.1.2                  |           py35_0         1.6 MB
    python-dateutil-2.5.3      |           py35_0         237 KB
    matplotlib-1.5.2           |      np111py35_3         3.9 MB
    ------------------------------------------------------------
                                           Total:        37.1 MB

The following NEW packages will be INSTALLED:

    cycler:          0.10.0-py35_0      
    freetype:        2.6.3-1            
    libpng:          1.6.23-0           
    matplotlib:      1.5.2-np111py35_3  
    nomkl:           1.0-0              
    numpy:           1.11.1-py35_nomkl_0 [nomkl]
    openssl:         1.0.2h-1           
    pip:             8.1.2-py35_0       
    pyparsing:       2.1.4-py35_0       
    python:          3.5.2-0            
    python-dateutil: 2.5.3-py35_0       
    pytz:            2016.4-py35_0      
    readline:        6.2-2              
    setuptools:      23.0.0-py35_0      
    six:             1.10.0-py35_0      
    sqlite:          3.9.2-0            
    tk:              8.5.19-0           
    wheel:           0.29.0-py35_0      
    xz:              5.0.5-1            
    zlib:            1.2.8-3            

Proceed ([y]/n)? y

Fetching packages ...
nomkl-1.0-0.ta 100% |################################| Time: 0:00:00 401.98 kB/s
openssl-1.0.2h 100% |################################| Time: 0:00:03 814.46 kB/s
tk-8.5.19-0.ta 100% |################################| Time: 0:00:01   1.46 MB/s
zlib-1.2.8-3.t 100% |################################| Time: 0:00:00 423.31 kB/s
libpng-1.6.23- 100% |################################| Time: 0:00:00 744.05 kB/s
python-3.5.2-0 100% |################################| Time: 0:00:10   2.13 MB/s
freetype-2.6.3 100% |################################| Time: 0:00:00   1.06 MB/s
numpy-1.11.1-p 100% |################################| Time: 0:00:01   1.80 MB/s
pyparsing-2.1. 100% |################################| Time: 0:00:00 358.75 kB/s
pytz-2016.4-py 100% |################################| Time: 0:00:00 438.43 kB/s
setuptools-23. 100% |################################| Time: 0:00:00 714.01 kB/s
six-1.10.0-py3 100% |################################| Time: 0:00:00 182.66 kB/s
cycler-0.10.0- 100% |################################| Time: 0:00:00 140.81 kB/s
pip-8.1.2-py35 100% |################################| Time: 0:00:01   1.47 MB/s
python-dateuti 100% |################################| Time: 0:00:00 557.17 kB/s
matplotlib-1.5 100% |################################| Time: 0:00:01   2.11 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
#
# To activate this environment, use:
# $ source activate debug
#
# To deactivate this environment, use:
# $ source deactivate
#

$ source activate debug
discarding /Users/tom/miniconda3/bin from PATH
prepending /Users/tom/miniconda3/envs/debug/bin to PATH

$ python -c 'import matplotlib; print(matplotlib.__version__)'
1.5.2

$ python -c 'from matplotlib._path import *'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/Users/tom/miniconda3/envs/debug/lib/python3.5/site-packages/matplotlib/_path.cpython-35m-darwin.so, 2): Library not loaded: @rpath/./libstdc++.6.dylib
  Referenced from: /Users/tom/miniconda3/envs/debug/lib/python3.5/site-packages/matplotlib/_path.cpython-35m-darwin.so
  Reason: image not found
```

**Comment by ocefpaf** [comment]
@astrofrog install `libgcc` to "satisfy" matplotlib's dependency on `libgcc` b/c it was compiled with `numpy`+`openblas`.

Ping @pelson I really think we should re-examine this `conda-forge`'s `numpy`.

**Comment by astrofrog** [comment]
@ocefpaf - ok, thanks! It might make sense to add ``matplotlib._path`` to the list of imports to test in the recipe?

**Comment by ocefpaf** [comment]
> @ocefpaf - ok, thanks! It might make sense to add ``matplotlib._path`` to the list of imports to test in the recipe?

The recipe is OK and that test will pass b/c at build and run-time in the "correct" numpy+openblas was downloaded.

The problem is lack of consistency in our stack. When conda-forge added the numpy with openblas we forced at new dependency on `libgcc` and software like `matplotlib` linked to the `libstdc++`.

The solutions are:

1. remove numpy+openblas from conda-forge
2. find a better way to ship only the Fortran libs to avoid acidental linking to `libstdc++`.
3. create a new matrix item for numpy (like we have for the versions when we use `x.x`)

IMO 1 is a low hanging fruit and would save a lot of pain. 2 is a long term goal and we need to think about it to make it right. 3 is a no-no!

**Comment by astrofrog** [comment]
If 2. will take some time, then I think 1. would indeed be a good short-term solution 👍

**Comment by jakirkham** [comment]
I fail to see how that helps the situation. As can be seen by `conda list` that @astrofrog included above, he is already not using our `numpy`. In fact, `defaults` has a newer version of `numpy` than we have currently.

Though, at the end of the day, the solution here like everything else that is being built on Mac is to use the same C++ runtime as everything else, which is not occurring here as evidenced by this bug report. Given all of `matplotlibs` dependencies use C, this shouldn't require so much work. In fact, here is a PR ( https://github.com/conda-forge/matplotlib-feedstock/pull/40 ). Worked fine on a build on my Mac.

**Comment by ocefpaf** [comment]
> I fail to see how that helps the situation.

Simply by having our matplotlib and the rest of the stack not linking to `libstdc++` and playing nice with the two numpy version available in defaults (`mkl` and `no_mkl`).

> As can be seen by conda list that @astrofrog included above, he is already not using our `numpy`.

We all saw that and that **is** the problem. In this scenario he specified the `no_mkl`, under different scenarios in a huge amount of issues opened in conda-forge the same happens when nothing is specified and `defaults` `numpy` is picked up by conda. The only way around it is to either install `libgcc` or force install conda-forge's `numpy`.

@astrofrog sorry that the stack is currently broken. But at least there is a workaround and hopefully people will come to a solution rather than insisting that there is no problem.

**Comment by jakirkham** [comment]
> > I fail to see how that helps the situation.

> Simply by having our matplotlib and the rest of the stack not linking to `libstdc++` and playing nice with the two numpy version available in defaults (`mkl` and `no_mkl`).

Removing `numpy` doesn't change that though. Rebuilding `matplotlib` as is with a build bump and that removal might change that, but then it will use the system `libstdc++` as is. As mentioned before, that is still a problem. Just a different problem.

> But at least there is a workaround and hopefully people will come to a solution rather than insisting that there is no problem.

Sorry, that is not accurate. I did note there is a problem and proposed a solution. What was unclear?

**Comment by ocefpaf** [comment]
> Removing `numpy` doesn't change that though.

After rebuilding the stack it will.
