### ISSUE TITLE
Token on CircleCI

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/matplotlib-feedstock#5]
No BINSTAR_TOKEN present, so no upload is taking place.
    The distribution just built is not already available on conda-forge's main channel.

**Comment by ocefpaf** [comment]
@pelson I remember manually inserting the Token when I create my CircleCI config.  Not sure how are we going to manage that here.

**Comment by pelson** [comment]
> I remember manually inserting the Token when I create my CircleCI config. Not sure how are we going to manage that here.

It is all done for you by conda-smithy. :wink: 

Just ensure your BINSTAR_TOKEN environment variable is set appropriately.

**Comment by pelson** [comment]
Oh, I see. Woops....

**Comment by ocefpaf** [comment]
Closed by #9
