### ISSUE TITLE
Switch requirements pyqt to qt

### ISSUE THREAD

**Issue by akorosov** [conda-forge/matplotlib-feedstock#57]
Matplotlib depends on pyqt which can be found only in anaconda. The latest conda-forge/qt build conflicts with pyqt and prevents installation of matplotlib and basemap. Seems to be problem of qt? We can avoid it by replacing pyqt requirements by qt.

**Comment by ocefpaf** [comment]
@akorosov which platform are seeing this problem? In theory `conda-forge`'s `Qt` and `pyqt`  should be consistent on Linux (thanks to @ccordoba12) but we are not building `Qt` on `OS X` and Windows. So far `defaults` filled that role with a `Qt` compiled against `jpeg 8*` but that is a source of problems when sometimes depending on the package combination (specially on Windows+Python 3.5).

**Comment by akorosov** [comment]
This is invalid. Since there is pyqt in conda-forge, everything is OK.

**Comment by ocefpaf** [comment]
>This is invalid. Since there is pyqt in conda-forge, everything is OK.

You probably hit the few hours while @ccordoba12 was preparing the `pyqt` recipe yesterday.
