### ISSUE TITLE
missing libgcc 

### ISSUE THREAD

**Issue by bgruening** [conda-forge/matplotlib-feedstock#61]
In our minimal Docker builds we see this error if we are using matplotlib.

```
[Sep 26 22:27:46] STEP Run image [quay.io/mulled/multiqc:0.8dev0--py35_0] with command [[multiqc --version]]
[Sep 26 22:27:46] DEBU Creating container [step-66ab04b33d]
[Sep 26 22:27:49] DEBU Created container [e07531f9e567 step-66ab04b33d], starting it
[Sep 26 22:27:57] DEBU Container [e07531f9e567 step-66ab04b33d] started, waiting for completion
[Sep 26 22:28:05] SERR ##### ERROR! MatPlotLib library could not be loaded!    #####
[Sep 26 22:28:05] SERR ##### Flat plots will instead be plotted as interactive #####
[Sep 26 22:28:05] SERR libstdc++.so.6: cannot open shared object file: No such file or directory
```

**Comment by jakirkham** [comment]
That seems a bit surprising. Does the system not have `libstdc++.so.6`? This is just using CentOS 6 to build FYI.

**Comment by jakirkham** [comment]
I suppose that's up for discussion. It may make more sense if we build and use our own compiler. However, at present, we assume the user has CentOS 6 or equivalent and use devtoolset-2.

**Comment by bgruening** [comment]
@jakirkham what happend to the decision that every package should depend on `gcc` resp. `llvm`?

**Comment by jakirkham** [comment]
So I think we are still following that, but these are two different issues.

**Comment by ocefpaf** [comment]
@bgruening closing this as stale. Please re-open if you still wishes to discuss this (or an updated version of it for the new compilers.)

**Comment by bgruening** [comment]
@ocefpaf its fine. conda-build 3 has fixed this issue.
